version: "3"

services:

  # Aplicacion test
  aplicacion-test:
    image: aplicacion-test
    volumes:
      - ./logs/aplicacion-test.log:/tmp/aplicacion-test.log
      - ./logs/access_log.log:/tmp/access_log.log
    environment:
      JAVA_TOOL_OPTIONS: -javaagent:./opentelemetry-javaagent.jar
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://agent:4317
      OTEL_SERVICE_NAME: aplicacion-test
      OTEL_TRACES_EXPORTER: otlp
    ports:
      - "8080:8080"

  # Encargado de ejecutar la shellscript para simular trafico
  simulador-carga:
    image: curlimages/curl:latest
    volumes:
      - ../aplicacion-test/simulador-carga.sh:/tmp/simulador-carga.sh
    command: /bin/sh -c "/tmp/simulador-carga.sh"
  
  agent:
    image: grafana/agent:v0.25.1
    volumes:
      # Configuracion del agente
      - ./config/agent.yaml:/etc/agent-config/agent.yaml
      # Archivos de logs
      - ./logs/aplicacion-test.log:/tmp/aplicacion-test.log
      - ./logs/access_log.log:/tmp/access_log.log
      - /tmp/agent:/etc/agent
    entrypoint:
      - /bin/agent
      - -config.file=/etc/agent-config/agent.yaml
      - -metrics.wal-directory=/tmp/agent/wal
      - -enable-features=integrations-next
      - -config.expand-env
      - -config.enable-read-api
    environment:
      HOSTNAME: agent
    ports:
      - "4317:4317"
