{
 "title": "Dashboard de Prueba",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total de Solicitudes - Loki",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(path) (count_over_time({job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` |= \"/backend\" [$__interval]))",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum by(path) (count_over_time({job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` |= \"/frontend\" [$__interval]))",
     "legendFormat": "{{path}}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Total de Visitas - Loki",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(job) (count_over_time({job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` != \"/metrics\" [$__interval]))",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Solicitudes por codigo de estado - Loki",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time({job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` != \"/metrics\" [$__interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total Bytes enviados - Loki",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (path) (sum_over_time({job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` |= \"/frontend\" | unwrap size [1m]))",
     "legendFormat": "{{path}}"
    },
    {
     "expr": "sum by (path) (sum_over_time({job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` |= \"/backend\" | unwrap size [1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Codigos de estado HTTP en un tiempo por minuto - Loki",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 5 },
   "targets": [
    {
     "expr": "sum by (status) (count_over_time( {job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` != \"/metrics\" [1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Servicio Up/Down - Prometheus",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "up{job=\"aplicacion-test\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Requests por Minuto - Prometheus",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (path) (rate (requests_total[1m])) * 60",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latencia - Prometheus",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (path) (rate(request_duration_histogram_bucket{}[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percentil 90% - Tamaño respuesta - Loki",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "quantile_over_time (0.90, {job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` != \"/metrics\" | unwrap size [1m] ) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Requests por Minuto - Prometheus",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (path) (rate(requests_total{job=\"aplicacion-test\"} [1m]) * 60)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Tasa de Error - Loki",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "sum by (path) (rate( {job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` != \"/metrics\" | status !=200 [1m])) / sum by (path) (rate( {job=\"tomcat-access\"} | pattern `<_> - - <_> \"<method> <path> <_>\" <status> <size>` != \"/metrics\" [1m])) * 100",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Latencia - Prometheus",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(request_duration_histogram_bucket{}[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Logs - Loki",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{job=\"aplicacion-test\"}"
    }
   ]
  }
 ]
}